version: "3"

services:
  structural:
    build:
      context: ./
      dockerfile: DockerfileDev
    volumes:
      - C:\Users\lachl\OneDrive\Documents\GitHub\LoopStructural:/home/jovyan/LoopStructural
      - C:\Users\lachl\OneDrive\Documents\Loop\notebooks:/home/jovyan/notebooks
    ports:
      - 8888:8888
      - 8050:8050
      - 8080-8090:8080-8090
    # command: jupyter notebook --ip='0.0.0.0' --NotebookApp.token='' --no-browser
