version: "3"

services:
  structural:
    build: 
      context: ./
      dockerfile: DockerfileDev
    volumes:
      - /home/lgrose/dev/python/LoopStructural/:/home/jovyan/LoopStructural
      - /home/lgrose/LoopStructural/:/home/jovyan/notebooks
    ports:
      - 8888:8888
      - 8050:8050
      - 8080-8090:8080-8090

    
