name: publish_conda

on:
  release:
    types: [created, edited]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Loop Conda
        uses: Loop3D/conda-publish-action@1.8
        with:
          subdir: "conda"
          anacondatoken: ${{ secrets.CONDA }}
          platforms: "win osx linux"
