name: Run tests and try to build wheel

on: ['push','pull_request']

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.10.1-0/Miniforge-pypy3-4.10.1-0-Linux-x86_64.sh
          channels: anaconda,conda-forge,loop3d,conda-forge/label/cf202003
          python-version: 3.7
      - name: Building and uploading m2l pkg for linux, osx and windows
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
            conda install cython numpy scipy matplotlib -y
            pip install lavavu-osmesa 
            pip install .
            cd docs
            pip install -r requirements.txt
            make html