name: Run tests and try to build wheel

on: ['push','pull_request']
jobs:
  conda-deploy:
    name: Continuous integration ${{ matrix.os }} python ${{ matrix.python-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest",  "windows-latest"] #"macos-latest",
        python-version: ["3.7","3.8","3.9"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python }} 
      - name: Installing dependencies
        shell: bash -l {0}
        run: |
          conda install -c conda-forge cython numpy scipy scikit-image scikit-learn pyamg flake8 pytest networkx osqp numba statsmodels scikit-fmm 
      - name: Checking formatting of code
        shell: bash -l {0}
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 LoopStructural --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            flake8 LoopStructural --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Building and install 
        shell: bash -l {0}
        run: |
          pip install .
      - name: pytest
        shell: bash -l {0}
        run: |
          pytest
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          auto-activate-base: true
          installer-url: https://github.com/conda-forge/miniforge/releases/download/4.10.1-0/Miniforge-pypy3-4.10.1-0-Linux-x86_64.sh
          channels: anaconda,conda-forge,loop3d,conda-forge/label/cf202003
          python-version: 3.8
      - name: Build documentation 
        shell: bash -l {0}
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
            conda install -c conda-forge theano cython numpy pandas imageio scipy matplotlib  sphinx sphinx-gallery sphinxcontrib-bibtex pydata-sphinx-theme myst-parser scikit-learn scikit-image pyamg flake8 pytest networkx python=3.9   -y
            pip install lavavu-osmesa 
            python setup.py install build_ext --inplace
            cd docs
            make html