name: Run tests and try to build wheel

on: ['push','pull_request']

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          sudo apt-get install pybind11-dev mesa-common-dev mesa-utils libgl1-mesa-dev gcc build-essential 
          python -m pip install --upgrade pip
          pip install pybind11
          pip install -r requirements.txt
      - name: Build library
        run: |
          python setup.py install build_ext --inplace
      - name: Checking formatting of code
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 LoopStructural --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 LoopStructural --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
  build-windows:
    runs-on: windows-latest
    needs: flake8
    strategy:
      matrix:
        python: ['3.6','3.7','3.8']
    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/action-setup-conda@v1
      with:
        python-version: ${{ matrix.python }} 
        activate-environment: loop    
    - name: Installing dependencies
      shell: bash -l {0}
      run: |
        python --version
        pip install -r requirements.txt
        conda info
        conda list
    - name: Building Loop wheel and installing
      shell: bash -l {0}
      run: |
        python setup.py bdist_wheel
        python setup.py install build_ext --inplace
    
    - name: Running tests
      shell: bash -l {0}
      run: |
        pip install pytest
        pytest

  
  ubuntu-build:
    runs-on: ubuntu-latest
    needs: flake8
    strategy:
      matrix:
        python: ['3.6','3.7','3.8']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          sudo apt-get install pybind11-dev mesa-common-dev mesa-utils libgl1-mesa-dev gcc build-essential 
          python -m pip install --upgrade pip
          pip install pybind11
          pip install -r requirements.txt
      - name: Build library
        run: |
          python setup.py install build_ext --inplace
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
 
